//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace OnlineStore.Server.ThumbnailServiceImplService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.org/", ConfigurationName="OnlineStore.Server.ThumbnailServiceImplService.ThumbnailService")]
    public interface ThumbnailService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.org/ThumbnailService/downloadThumbnailRequest", ReplyAction="http://example.org/ThumbnailService/downloadThumbnailResponse")]
        System.Threading.Tasks.Task<OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailResponse> downloadThumbnailAsync(OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadThumbnailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadThumbnail", Namespace="http://example.org/", Order=0)]
        public OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailRequestBody Body;
        
        public downloadThumbnailRequest()
        {
        }
        
        public downloadThumbnailRequest(OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadThumbnailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public downloadThumbnailRequestBody()
        {
        }
        
        public downloadThumbnailRequestBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadThumbnailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadThumbnailResponse", Namespace="http://example.org/", Order=0)]
        public OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailResponseBody Body;
        
        public downloadThumbnailResponse()
        {
        }
        
        public downloadThumbnailResponse(OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadThumbnailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] @return;
        
        public downloadThumbnailResponseBody()
        {
        }
        
        public downloadThumbnailResponseBody(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ThumbnailServiceChannel : OnlineStore.Server.ThumbnailServiceImplService.ThumbnailService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ThumbnailServiceClient : System.ServiceModel.ClientBase<OnlineStore.Server.ThumbnailServiceImplService.ThumbnailService>, OnlineStore.Server.ThumbnailServiceImplService.ThumbnailService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ThumbnailServiceClient() : 
                base(ThumbnailServiceClient.GetDefaultBinding(), ThumbnailServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ThumbnailServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThumbnailServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ThumbnailServiceClient.GetBindingForEndpoint(endpointConfiguration), ThumbnailServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThumbnailServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ThumbnailServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThumbnailServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ThumbnailServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThumbnailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailResponse> OnlineStore.Server.ThumbnailServiceImplService.ThumbnailService.downloadThumbnailAsync(OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailRequest request)
        {
            return base.Channel.downloadThumbnailAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailResponse> downloadThumbnailAsync(string arg0)
        {
            OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailRequest inValue = new OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailRequest();
            inValue.Body = new OnlineStore.Server.ThumbnailServiceImplService.downloadThumbnailRequestBody();
            inValue.Body.arg0 = arg0;
            return ((OnlineStore.Server.ThumbnailServiceImplService.ThumbnailService)(this)).downloadThumbnailAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ThumbnailServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MessageEncoding = WSMessageEncoding.Mtom;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ThumbnailServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9999/ws/hello");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ThumbnailServiceClient.GetBindingForEndpoint(EndpointConfiguration.ThumbnailServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ThumbnailServiceClient.GetEndpointAddress(EndpointConfiguration.ThumbnailServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ThumbnailServiceImplPort,
        }
    }
}
